services:

  image-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dogcat_image_api
    ports:
      - "8000:8000"
    networks:
      - dogcat-network
    depends_on:
      - mlflow

  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: dogcat_streamlit
    ports:
      - "8501:8501"
    networks:
      - dogcat-network
    depends_on:
      - image-api
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    networks:
      - dogcat-network
    volumes:
      - ./mlruns:/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow
      --host 0.0.0.0
      --port 5000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - dogcat-network
    depends_on:
      - image-api
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle

  grafana:
    build:
      context: ./monitoring/grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - dogcat-network
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning

networks:
  dogcat-network:

volumes:
  grafana-storage: